version: "3.8"
services:
  backend:
    container_name: backend
    build: ./backend
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - 4000:80
